### ISSUE TITLE
Rename the library because "coon" is a racial slur

### ISSUE THREAD

**Issue by klausi** [comtihon/coon#59] opened 2018-02-12 22:07 UTC
* "Coon" is a racial slur and will turn away users, contributors and companies
* It is well known as racial slur, ranking second after fauna names on Wikipedia https://en.wikipedia.org/wiki/Coon
* Conferences will reject presentations about this library because using the name violates their code of conduct.

More reasoning can be found on the [erlang-questions](http://erlang.org/pipermail/erlang-questions/2018-February/094770.html) mailing list.

**Comment by joshmillard** [comment] 2018-02-13 00:05
Just pointedly concurring with klausi and those expressing surprise and concern on the mailing list.  Irrespective of the author's original intent, it's a word that has unambiguously had a long, ugly, racist history, one that very much extends into living memory.  Moving to a different name for the package is a simple and respectful way to dislodge some needless and deeply unfortunate semantic baggage from the project.

**Comment by NickDickinsonWilde** [comment] 2018-02-13 00:20
I'm in an area that that has racoon's freaking everywhere (2 days without seeing them or their tracks is unusual) and that particular racial slur isn't used. That said, I absolutely know of it from reading stuff online. It would be easy to not know it depending on where you are from, however, not knowing it will not reduce the harm of using it. So +1 please change it.

**Comment by eaton** [comment] 2018-02-13 01:46
Naming things is hard, and when there are unrealized cross-cultural implications it's easy to step on a metaphorical garden rake. Making the initial naming decision without any ill intent is totally fine, but when one realizes what has happened, changing it is the decent thing to do.

If names don't matter and it's all about the code, renaming it to avoid future problems should be utterly unremarkable. Doing it now, before the code becomes a successful part of the broader ecosystem, would be a super smart move.

**Comment by philsturgeon** [comment] 2018-02-13 06:31
Once a friend named a package Factory Muff, and I pointed out that in some countries that’s slang for something NSFW. They said “ooos, I had no idea!” and changed the project name. It was great.

This package was a port of Factory Girl. Some folks pointed out their troubles with that name, and the project changed it. It was great.

It’s not about something definitively being “good” or “bad”, it’s about asking yourself “do I care enough about the people who I’m upsetting by continuing to do this thing they’ve told me they don’t like?”

If you find out you’re upsetting people and keep doing the thing, then you’re being a big-ol’ jerk. If you find you’re upsetting people but you listen to their feedback and act accordingly, then you’re being a standard stand-up human being. Maybe do that one.

**Comment by comtihon** [comment] 2018-02-13 08:16
Ok, as I've already said in the mailing list - I named the project 'coon' because raccoon was occupied.
If you check translation from russian to english (english is not my native language) in [google](https://translate.google.ru/#ru/en/%D0%B5%D0%BD%D0%BE%D1%82) -> there are 3 oppotunities: raccoon (occupied), racoon (looks like 1st variant) and coon (free). 
So my logic was simple - I've just selected coon. No library with this name exists and it is shorter and easier to write than raccoon.
For now I will start renaming process of this project. But you must understand it is not so fast, as I don't have much time (I work on this and several other open source projects in my free time and nobody pays me for this). And there are a lot of work to do like:
* rename git repos (client and server)
* fix travis integration
* replace all `coon` code occurrences in code, templates 
* register new project in pip and remove old
* create new subdomain and link to the server
* change server frontend
* change server's configuration related to the new subdomain.
* replace `coon` occurrences in all articles I've written (and probably their links)

It may seem like a half an hour work, but sometimes I even don't have time for cooking... 
I think that project will be renamed completely after this weekend.

**Comment by klausi** [comment] 2018-02-13 08:37
Thanks a lot for your understanding @comtihon !

**Comment by comtihon** [comment] 2018-02-13 09:39
I also think you should warn authors of [other](https://github.com/search?utf8=%E2%9C%93&q=coon&type=) 190 repositories on github.

**Comment by Havvy** [comment] 2018-02-13 10:28
This issue should probably be locked to contributors before bad things happen to it.

But before it is, for anybody else reading this, when the project name has a racist connotation, then it opens up any business using it to hostile workplace lawsuits from employees, so legal departments will stop people from using said project at work. For any project that wants to be used widely in a programming ecosystem, making sure it can be used professionally is important, so renaming just because of that would be prudent.

**Comment by retran** [comment] 2018-02-13 12:27
Please, don't.

Why Pidora(https://wiki.cdot.senecacollege.ca/wiki/Pidora_Russian), Gimp(https://www.urbandictionary.com/define.php?term=gimp) and Git(https://en.wikipedia.org/wiki/Git_(slang)) don't insult anyone?

**Comment by AthenaEryma** [comment] 2018-02-13 15:36
Pidora does, the page you linked to is explaining that they are searching for an alternative name. 

Personally I’ve always hated the name “GIMP” and desperately wish they would change it.  It makes the program embarrassing to talk about or recommend to non-software folks who just want a photoshop alternative.  However, it’s been that way for a long time and changing it now would be a big effort. This project is relatively new, and it would be best to change it before there are a zillion blog posts/videos/etc about it, as there are about GIMP and you get into the situation of having to deal with a name switch after 20 years of inertia. 

Git, unlike “coon” or “gimp”, is not to my knowledge used as a slur against any particular class of people. I’m still not a huge fan of the name, but I don’t think it will put off large numbers of people from using it, or be read as discriminatory.

**Comment by crestenstclair** [comment] 2018-02-13 15:56
@comtihon is there anything I can do to help you out? I think it's REALLY unfortunate and I believe you that you didn't understand the connotations!

**Comment by philsturgeon** [comment] 2018-02-13 16:02
Everybody stop, it's fine, he's changing the name.

**Comment by retran** [comment] 2018-02-13 16:41
@gwbrown Pidora mantainers have been doing this for 5 years already (look at page history). And this is very offensive word for LGBT. Why doesn't anyone care? Because typical sjw doesn't speak russian.

**Comment by seancribbs** [comment] 2018-02-13 16:45
@comtihon Please lock the thread.

**Comment by comtihon** [comment] 2018-02-18 21:20
Hi,

As promised, I have done renaming the tool. And now it is called 'Enot' [yenot] - that is raccoon in Russian. 
My appology for not being answering the questions before - I was extremely busy with my personal stuff and renaming in general. So further in letter you'll see links on updated everything :) and answers on most questions from the mailing list.


Here are the updated links:
https://github.com/comtihon/enot - client
https://github.com/comtihon/enot_auto_builder - server
https://enot.justtech.blog/ - site
and updated articles:
https://justtech.blog/2018/01/07/create-erlang-service-with-enot/
https://justtech.blog/2018/02/11/erlang-service-easy-deploy-with-enot/

The GiHhub application and it's pip package are also renamed to enot.

Now I'll try to answer your questions:
First, Enot is not just another build system with new configuration format (eh, we already have two), but It is an easy deploy tool. You prepare your installation instructions and every user can install your package
via "enot install ..." CLI command. That's the main idea: to have something comparable with Python's pip.
Also I tried my best to design modern tool, similar to what they have in Java and Python worlds.
I took the best:
* prebuilt deps [Maven, Pip]. Now all CI/docker builds will be much faster
* an easy deploy [Pip]. 
* multiple environment configuration [Java]. See https://github.com/comtihon/enot/blob/master/docs/templating.md#appsrc-advanced-templates for more details.
* automatic name/version fill in at app.conf and relx.conf. Yes, I think that  manual handling of versions and constants is a little bit outdated and not practical. Especially, when you have to modify multiple files.  

Second, I believe Json coniguration is better for devOps, but if you don't want to learn it: use rebar or erlang.mk config - Enot understands them as well.

Third, there were some questions about security. I've added document here https://github.com/comtihon/enot/blob/master/docs/packaging_and_security.md 
Main idea is: nobody can upload prebuilt package to EnotHub. You can only ask Enot Build Server to fetch sources from GitHub and build package.
Also, do you really use third-party github deps in production? I beleive not. So just fork dep you need, add it to EnotHub and use. Enot was designed to be fork-compatible.  

If your company is big enough to afford private git (gitlab), artifactory/nexus, ets. you can just run your private Enot Build server and switch all Enot clients to it to gain even more security.

As for cryptography package checks - I also find it important and I'll add it in a few weeks (still a little bit busy).

Many thanks to people who advocate me and my appologies to people who felt hurt. 

I hope nothing will stop you to use this tool at work now :).

**Closed as completed by comtihon** 2018-02-18 21:20 UTC
